-- ZingBite Database Schema Reference
-- Generated from Hibernate entities
-- Database: ZingBite (MySQL)

CREATE TABLE IF NOT EXISTS `user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(255) DEFAULT NULL,
  `EMAIL` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `PHONENUMBER` BIGINT DEFAULT NULL,
  `ADDRESS` VARCHAR(255) DEFAULT NULL,
  `CREATEDON` DATETIME DEFAULT NULL,
  `LASTLOGIN` DATETIME DEFAULT NULL,
  `role` VARCHAR(255) DEFAULT 'customer',
  `latitude` DOUBLE DEFAULT NULL,
  `longitude` DOUBLE DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `rider_status` VARCHAR(255) DEFAULT NULL,
  `vehicle_type` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`userid`)
);

CREATE TABLE IF NOT EXISTS `restaurant` (
  `RESTAURANTID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANTNAME` VARCHAR(255) DEFAULT NULL,
  `DELIVERYTIME` VARCHAR(255) DEFAULT NULL,
  `CUSINETYPE` VARCHAR(255) DEFAULT NULL,
  `ADDRESS` VARCHAR(255) DEFAULT NULL,
  `RATINGS` FLOAT DEFAULT NULL,
  `ISACTIVE` TINYINT DEFAULT NULL,
  `ADMINID` INT DEFAULT NULL,
  `IMAGEPATH` VARCHAR(255) DEFAULT NULL,
  `latitude` DOUBLE DEFAULT NULL,
  `longitude` DOUBLE DEFAULT NULL,
  `ISOPEN` TINYINT DEFAULT 1,
  `TOTALORDERS` INT DEFAULT 0,
  `TOTALIMPRESSIONS` INT DEFAULT 0,
  PRIMARY KEY (`RESTAURANTID`)
);

CREATE TABLE IF NOT EXISTS `menu` (
  `MENUID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANTID` INT DEFAULT NULL,
  `MENUNAME` VARCHAR(255) DEFAULT NULL,
  `PRICE` DOUBLE DEFAULT NULL,
  `ITEMDESCRIPTION` VARCHAR(255) DEFAULT NULL,
  `ISAVAILABLE` TINYINT DEFAULT NULL,
  `IMAGEPATH` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`MENUID`),
  KEY `idx_menu_restaurant` (`RESTAURANTID`)
);

CREATE TABLE IF NOT EXISTS `orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `restaurantRefId` INT DEFAULT NULL,
  `userId` INT DEFAULT NULL,
  `orderTime` VARCHAR(255) DEFAULT NULL,
  `totalAmount` FLOAT DEFAULT NULL,
  `orderStatus` VARCHAR(255) DEFAULT NULL,
  `statusUpdatedAt` DATETIME DEFAULT NULL,
  `paymentMethod` VARCHAR(255) DEFAULT NULL,
  `riderId` INT DEFAULT NULL,
  `gpsProgress` DOUBLE DEFAULT 0,
  `gpsCoordinates` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`orderId`),
  KEY `idx_orders_user` (`userId`),
  KEY `idx_orders_rider` (`riderId`),
  KEY `idx_orders_status` (`orderStatus`),
  KEY `idx_orders_restaurant` (`restaurantRefId`)
);

CREATE TABLE IF NOT EXISTS `orderitem` (
  `orderItemId` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT DEFAULT NULL,
  `menuId` INT DEFAULT NULL,
  `quantity` INT DEFAULT NULL,
  `subTotal` DOUBLE DEFAULT NULL,
  PRIMARY KEY (`orderItemId`)
);

CREATE TABLE IF NOT EXISTS `orderhistory` (
  `orderHistoryId` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT DEFAULT NULL,
  `userId` INT DEFAULT NULL,
  `orderDate` DATETIME DEFAULT NULL,
  `totalAmount` DOUBLE DEFAULT NULL,
  `orderStatus` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`orderHistoryId`)
);

CREATE TABLE IF NOT EXISTS `payment` (
  `paymentId` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT DEFAULT NULL,
  `transactionId` VARCHAR(255) DEFAULT NULL,
  `amount` DOUBLE DEFAULT NULL,
  `paymentMethod` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT 'PENDING',
  `createdAt` DATETIME DEFAULT NULL,
  `updatedAt` DATETIME DEFAULT NULL,
  PRIMARY KEY (`paymentId`)
);

CREATE TABLE IF NOT EXISTS `restaurant_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurantName` VARCHAR(255) DEFAULT NULL,
  `cuisineType` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `deliveryTime` VARCHAR(255) DEFAULT NULL,
  `imagePath` VARCHAR(255) DEFAULT NULL,
  `licenseNo` VARCHAR(255) DEFAULT NULL,
  `aadhaarNo` VARCHAR(255) DEFAULT NULL,
  `gstNo` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT 'Pending',
  `adminId` INT DEFAULT NULL,
  `submittedDate` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) DEFAULT NULL,
  `department` VARCHAR(255) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `posted_date` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT DEFAULT NULL,
  `candidate_name` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(255) DEFAULT NULL,
  `resume_url` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT 'Applied',
  `applied_date` VARCHAR(255) DEFAULT NULL,
  `user_id` INT DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `contact_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `subject` VARCHAR(255) DEFAULT NULL,
  `message` VARCHAR(1000) DEFAULT NULL,
  `submitted_date` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `chat_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT DEFAULT NULL,
  `application_id` INT DEFAULT NULL,
  `sender_id` INT DEFAULT NULL,
  `sender_name` VARCHAR(255) DEFAULT NULL,
  `receiver_id` INT DEFAULT NULL,
  `message_text` VARCHAR(1000) DEFAULT NULL,
  `timestamp` DATETIME DEFAULT NULL,
  `is_read` TINYINT DEFAULT 0,
  `read_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_chat_order_time` (`order_id`, `timestamp`),
  KEY `idx_chat_app_time` (`application_id`, `timestamp`)
);

CREATE TABLE IF NOT EXISTS `email_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT DEFAULT NULL,
  `recipient_email` VARCHAR(255) DEFAULT NULL,
  `subject` VARCHAR(255) DEFAULT NULL,
  `body` TEXT DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT 'PENDING',
  `sentDate` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `analytics_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT DEFAULT NULL,
  `eventType` VARCHAR(255) DEFAULT NULL,
  `search_query` VARCHAR(255) DEFAULT NULL,
  `eventData` TEXT DEFAULT NULL,
  `timestamp` DATETIME DEFAULT NULL,
  `ipAddress` VARCHAR(255) DEFAULT NULL,
  `userAgent` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_event_type` (`eventType`),
  KEY `idx_search_query` (`search_query`)
);
